<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ea7a144a-a3c8-448e-8747-159c1f2f1034</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PasswordManager.Application\PasswordManager.Application.csproj" />
    <ProjectReference
      Include="..\PasswordManager.Infrastructure\PasswordManager.Infrastructure.csproj" />
    <ProjectReference Include="..\PasswordManager.Domain\PasswordManager.Domain.csproj" />
  </ItemGroup>

</Project>